### ISSUE TITLE
Make the WPM meter window optionally not always on top

### ISSUE THREAD

**Issue by nsmarkop** [arxanas/plover_wpm_meter#9]
This is a request to add a toggle for always on top behavior of the WPM meter, similar to how windows like Paper Tape / Suggestions allow you to configure it. Currently the window is always on top.

**Comment by arxanas** [comment]
This should be added in the latest release (v0.2.1). It might take a few hours for the release to show up in the plugin manager. Open a new issue if you have any problems with it.
